/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import { faker } from "@faker-js/faker";

import { HttpResponse, delay, http } from "msw";
import type { RequestHandlerOptions } from "msw";

import { JobStatus, Type, Unit } from "./model";
import type {
  AlertDTO,
  JobInfo,
  ProductInfo,
  ProductResult,
  QuoteDTO,
  QuoteResult,
  SimpleQuoteDTO,
  StoreInfo,
} from "./model";

export const getGetApiAdminBatchAllResponseMock = (): JobInfo[] =>
  Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.number.int({ min: undefined, max: undefined }),
    enabled: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
    name: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    description: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    type: faker.string.alpha({ length: { min: 1, max: 20 } }),
    frequency: faker.string.alpha({ length: { min: 1, max: 20 } }),
    status: faker.helpers.arrayElement(Object.values(JobStatus)),
    lastResult: faker.helpers.arrayElement(Object.values(JobStatus)),
    lastRunTime: `${faker.date.past().toISOString().split(".")[0]}Z`,
    nextExecTime: `${faker.date.past().toISOString().split(".")[0]}Z`,
    parameters: faker.helpers.arrayElement([
      {
        [faker.string.alphanumeric(5)]: faker.string.alpha({
          length: { min: 10, max: 20 },
        }),
      },
      undefined,
    ]),
  }));

export const getGetApiAdminStoreSearchResponseMock = (): StoreInfo[] =>
  Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.helpers.arrayElement([
      faker.number.int({ min: undefined, max: undefined }),
      undefined,
    ]),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    address: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    storeGroupLogoPath: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    url: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
  }));

export const getGetApiCommonLatestDealsResponseMock = (
  overrideResponse: Partial<QuoteResult> = {},
): QuoteResult => ({
  results: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      productInfo: faker.helpers.arrayElement([
        {
          id: faker.helpers.arrayElement([
            faker.number.int({ min: undefined, max: undefined }),
            undefined,
          ]),
          name: faker.string.alpha({ length: { min: 1, max: 20 } }),
          imgUrl: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
          ]),
          desc: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
          ]),
          gtin: faker.helpers.arrayElement([
            faker.helpers.fromRegExp("^([0-9]{8}|[0-9]{12,14})$"),
            undefined,
          ]),
          unit: faker.helpers.arrayElement(Object.values(Unit)),
          latestQuotes: faker.helpers.arrayElement([
            Array.from(
              { length: faker.number.int({ min: 1, max: 10 }) },
              (_, i) => i + 1,
            ).map(() => ({
              productName: faker.helpers.arrayElement([
                faker.string.alpha({ length: { min: 10, max: 20 } }),
                undefined,
              ]),
              productImgPath: faker.helpers.arrayElement([
                faker.string.alpha({ length: { min: 10, max: 20 } }),
                undefined,
              ]),
              productId: faker.helpers.arrayElement([
                faker.number.int({ min: undefined, max: undefined }),
                undefined,
              ]),
              storeInfo: faker.helpers.arrayElement([
                {
                  id: faker.helpers.arrayElement([
                    faker.number.int({ min: undefined, max: undefined }),
                    undefined,
                  ]),
                  name: faker.string.alpha({ length: { min: 10, max: 20 } }),
                  address: faker.helpers.arrayElement([
                    faker.string.alpha({ length: { min: 10, max: 20 } }),
                    undefined,
                  ]),
                  storeGroupLogoPath: faker.helpers.arrayElement([
                    faker.string.alpha({ length: { min: 10, max: 20 } }),
                    undefined,
                  ]),
                  url: faker.helpers.arrayElement([
                    faker.string.alpha({ length: { min: 10, max: 20 } }),
                    undefined,
                  ]),
                },
                undefined,
              ]),
              quoteDate: faker.date.past().toISOString().split("T")[0],
              price: faker.number.float({
                min: undefined,
                max: undefined,
                fractionDigits: 2,
              }),
              unitScale: faker.helpers.arrayElement([
                faker.number.float({
                  min: undefined,
                  max: undefined,
                  fractionDigits: 2,
                }),
                undefined,
              ]),
              unitPrice: faker.number.float({
                min: undefined,
                max: undefined,
                fractionDigits: 2,
              }),
              unit: faker.helpers.arrayElement([
                faker.string.alpha({ length: { min: 10, max: 20 } }),
                undefined,
              ]),
              discountType: faker.helpers.arrayElement([
                faker.helpers.arrayElement(Object.values(Type)),
                undefined,
              ]),
              discountPrice: faker.helpers.arrayElement([
                faker.number.float({
                  min: undefined,
                  max: undefined,
                  fractionDigits: 2,
                }),
                undefined,
              ]),
              multibuyQuantity: faker.helpers.arrayElement([
                faker.number.float({
                  min: undefined,
                  max: undefined,
                  fractionDigits: 2,
                }),
                undefined,
              ]),
            })),
            undefined,
          ]),
          stats: faker.helpers.arrayElement([
            {
              [faker.string.alphanumeric(5)]: faker.number.float({
                min: undefined,
                max: undefined,
                fractionDigits: 2,
              }),
            },
            undefined,
          ]),
          quantityPerItem: faker.helpers.arrayElement([
            faker.number.float({
              min: undefined,
              max: undefined,
              fractionDigits: 2,
            }),
            undefined,
          ]),
          itemPerBundle: faker.helpers.arrayElement([
            faker.number.int({ min: undefined, max: undefined }),
            undefined,
          ]),
          tags: faker.helpers.arrayElement([
            Array.from(
              { length: faker.number.int({ min: 1, max: 10 }) },
              (_, i) => i + 1,
            ).map(() => faker.string.alpha({ length: { min: 10, max: 20 } })),
            undefined,
          ]),
        },
        undefined,
      ]),
      storeInfo: faker.helpers.arrayElement([
        {
          id: faker.helpers.arrayElement([
            faker.number.int({ min: undefined, max: undefined }),
            undefined,
          ]),
          name: faker.string.alpha({ length: { min: 10, max: 20 } }),
          address: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
          ]),
          storeGroupLogoPath: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
          ]),
          url: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
          ]),
        },
        { id: faker.number.int({ min: undefined, max: undefined }) },
      ]),
      quoteDate: faker.date.past().toISOString().split("T")[0],
      price: faker.number.float({
        min: undefined,
        max: undefined,
        fractionDigits: 2,
      }),
      discountType: faker.helpers.arrayElement([
        faker.helpers.arrayElement(Object.values(Type)),
        undefined,
      ]),
      discountPrice: faker.helpers.arrayElement([
        faker.helpers.arrayElement([
          faker.number.float({
            min: undefined,
            max: undefined,
            fractionDigits: 2,
          }),
          null,
        ]),
        undefined,
      ]),
      multibuyQuantity: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
    })),
    undefined,
  ]),
  ...overrideResponse,
});

export const getGetApiProductAlertsResponseMock = (): SimpleQuoteDTO[] =>
  Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    productName: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    productImgPath: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    productId: faker.helpers.arrayElement([
      faker.number.int({ min: undefined, max: undefined }),
      undefined,
    ]),
    storeInfo: faker.helpers.arrayElement([
      {
        id: faker.helpers.arrayElement([
          faker.number.int({ min: undefined, max: undefined }),
          undefined,
        ]),
        name: faker.string.alpha({ length: { min: 10, max: 20 } }),
        address: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        storeGroupLogoPath: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        url: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
      },
      undefined,
    ]),
    quoteDate: faker.date.past().toISOString().split("T")[0],
    price: faker.number.float({
      min: undefined,
      max: undefined,
      fractionDigits: 2,
    }),
    unitScale: faker.helpers.arrayElement([
      faker.number.float({ min: undefined, max: undefined, fractionDigits: 2 }),
      undefined,
    ]),
    unitPrice: faker.number.float({
      min: undefined,
      max: undefined,
      fractionDigits: 2,
    }),
    unit: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    discountType: faker.helpers.arrayElement([
      faker.helpers.arrayElement(Object.values(Type)),
      undefined,
    ]),
    discountPrice: faker.helpers.arrayElement([
      faker.number.float({ min: undefined, max: undefined, fractionDigits: 2 }),
      undefined,
    ]),
    multibuyQuantity: faker.helpers.arrayElement([
      faker.number.float({ min: undefined, max: undefined, fractionDigits: 2 }),
      undefined,
    ]),
  }));

export const getGetApiProductAllResponseMock = (
  overrideResponse: Partial<ProductResult> = {},
): ProductResult => ({
  productList: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      id: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      name: faker.string.alpha({ length: { min: 1, max: 20 } }),
      imgUrl: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      desc: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      gtin: faker.helpers.arrayElement([
        faker.helpers.fromRegExp("^([0-9]{8}|[0-9]{12,14})$"),
        undefined,
      ]),
      unit: faker.helpers.arrayElement(Object.values(Unit)),
      latestQuotes: faker.helpers.arrayElement([
        Array.from(
          { length: faker.number.int({ min: 1, max: 10 }) },
          (_, i) => i + 1,
        ).map(() => ({
          productName: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
          ]),
          productImgPath: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
          ]),
          productId: faker.helpers.arrayElement([
            faker.number.int({ min: undefined, max: undefined }),
            undefined,
          ]),
          storeInfo: faker.helpers.arrayElement([
            {
              id: faker.helpers.arrayElement([
                faker.number.int({ min: undefined, max: undefined }),
                undefined,
              ]),
              name: faker.string.alpha({ length: { min: 10, max: 20 } }),
              address: faker.helpers.arrayElement([
                faker.string.alpha({ length: { min: 10, max: 20 } }),
                undefined,
              ]),
              storeGroupLogoPath: faker.helpers.arrayElement([
                faker.string.alpha({ length: { min: 10, max: 20 } }),
                undefined,
              ]),
              url: faker.helpers.arrayElement([
                faker.string.alpha({ length: { min: 10, max: 20 } }),
                undefined,
              ]),
            },
            undefined,
          ]),
          quoteDate: faker.date.past().toISOString().split("T")[0],
          price: faker.number.float({
            min: undefined,
            max: undefined,
            fractionDigits: 2,
          }),
          unitScale: faker.helpers.arrayElement([
            faker.number.float({
              min: undefined,
              max: undefined,
              fractionDigits: 2,
            }),
            undefined,
          ]),
          unitPrice: faker.number.float({
            min: undefined,
            max: undefined,
            fractionDigits: 2,
          }),
          unit: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
          ]),
          discountType: faker.helpers.arrayElement([
            faker.helpers.arrayElement(Object.values(Type)),
            undefined,
          ]),
          discountPrice: faker.helpers.arrayElement([
            faker.number.float({
              min: undefined,
              max: undefined,
              fractionDigits: 2,
            }),
            undefined,
          ]),
          multibuyQuantity: faker.helpers.arrayElement([
            faker.number.float({
              min: undefined,
              max: undefined,
              fractionDigits: 2,
            }),
            undefined,
          ]),
        })),
        undefined,
      ]),
      stats: faker.helpers.arrayElement([
        {
          [faker.string.alphanumeric(5)]: faker.number.float({
            min: undefined,
            max: undefined,
            fractionDigits: 2,
          }),
        },
        undefined,
      ]),
      quantityPerItem: faker.helpers.arrayElement([
        faker.number.float({
          min: undefined,
          max: undefined,
          fractionDigits: 2,
        }),
        undefined,
      ]),
      itemPerBundle: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      tags: faker.helpers.arrayElement([
        Array.from(
          { length: faker.number.int({ min: 1, max: 10 }) },
          (_, i) => i + 1,
        ).map(() => faker.string.alpha({ length: { min: 10, max: 20 } })),
        undefined,
      ]),
    })),
    undefined,
  ]),
  totalRecords: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  totalPages: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  pageSize: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  currentPage: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  ...overrideResponse,
});

export const getGetApiProductExtSourcesResponseMock = (): string[] =>
  Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, () =>
    faker.word.sample(),
  );

export const getGetApiProductGtinGtinResponseMock = (
  overrideResponse: Partial<ProductInfo> = {},
): ProductInfo => ({
  id: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  name: faker.string.alpha({ length: { min: 1, max: 20 } }),
  imgUrl: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  desc: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  gtin: faker.helpers.arrayElement([
    faker.helpers.fromRegExp("^([0-9]{8}|[0-9]{12,14})$"),
    undefined,
  ]),
  unit: faker.helpers.arrayElement(Object.values(Unit)),
  latestQuotes: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      productName: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      productImgPath: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      productId: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      storeInfo: faker.helpers.arrayElement([
        {
          id: faker.helpers.arrayElement([
            faker.number.int({ min: undefined, max: undefined }),
            undefined,
          ]),
          name: faker.string.alpha({ length: { min: 10, max: 20 } }),
          address: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
          ]),
          storeGroupLogoPath: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
          ]),
          url: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
          ]),
        },
        undefined,
      ]),
      quoteDate: faker.date.past().toISOString().split("T")[0],
      price: faker.number.float({
        min: undefined,
        max: undefined,
        fractionDigits: 2,
      }),
      unitScale: faker.helpers.arrayElement([
        faker.number.float({
          min: undefined,
          max: undefined,
          fractionDigits: 2,
        }),
        undefined,
      ]),
      unitPrice: faker.number.float({
        min: undefined,
        max: undefined,
        fractionDigits: 2,
      }),
      unit: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      discountType: faker.helpers.arrayElement([
        faker.helpers.arrayElement(Object.values(Type)),
        undefined,
      ]),
      discountPrice: faker.helpers.arrayElement([
        faker.number.float({
          min: undefined,
          max: undefined,
          fractionDigits: 2,
        }),
        undefined,
      ]),
      multibuyQuantity: faker.helpers.arrayElement([
        faker.number.float({
          min: undefined,
          max: undefined,
          fractionDigits: 2,
        }),
        undefined,
      ]),
    })),
    undefined,
  ]),
  stats: faker.helpers.arrayElement([
    {
      [faker.string.alphanumeric(5)]: faker.number.float({
        min: undefined,
        max: undefined,
        fractionDigits: 2,
      }),
    },
    undefined,
  ]),
  quantityPerItem: faker.helpers.arrayElement([
    faker.number.float({ min: undefined, max: undefined, fractionDigits: 2 }),
    undefined,
  ]),
  itemPerBundle: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  tags: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => faker.string.alpha({ length: { min: 10, max: 20 } })),
    undefined,
  ]),
  ...overrideResponse,
});

export const getPostApiProductNewResponseMock = (
  overrideResponse: Partial<ProductInfo> = {},
): ProductInfo => ({
  id: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  name: faker.string.alpha({ length: { min: 1, max: 20 } }),
  imgUrl: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  desc: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  gtin: faker.helpers.arrayElement([
    faker.helpers.fromRegExp("^([0-9]{8}|[0-9]{12,14})$"),
    undefined,
  ]),
  unit: faker.helpers.arrayElement(Object.values(Unit)),
  latestQuotes: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      productName: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      productImgPath: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      productId: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      storeInfo: faker.helpers.arrayElement([
        {
          id: faker.helpers.arrayElement([
            faker.number.int({ min: undefined, max: undefined }),
            undefined,
          ]),
          name: faker.string.alpha({ length: { min: 10, max: 20 } }),
          address: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
          ]),
          storeGroupLogoPath: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
          ]),
          url: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
          ]),
        },
        undefined,
      ]),
      quoteDate: faker.date.past().toISOString().split("T")[0],
      price: faker.number.float({
        min: undefined,
        max: undefined,
        fractionDigits: 2,
      }),
      unitScale: faker.helpers.arrayElement([
        faker.number.float({
          min: undefined,
          max: undefined,
          fractionDigits: 2,
        }),
        undefined,
      ]),
      unitPrice: faker.number.float({
        min: undefined,
        max: undefined,
        fractionDigits: 2,
      }),
      unit: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      discountType: faker.helpers.arrayElement([
        faker.helpers.arrayElement(Object.values(Type)),
        undefined,
      ]),
      discountPrice: faker.helpers.arrayElement([
        faker.number.float({
          min: undefined,
          max: undefined,
          fractionDigits: 2,
        }),
        undefined,
      ]),
      multibuyQuantity: faker.helpers.arrayElement([
        faker.number.float({
          min: undefined,
          max: undefined,
          fractionDigits: 2,
        }),
        undefined,
      ]),
    })),
    undefined,
  ]),
  stats: faker.helpers.arrayElement([
    {
      [faker.string.alphanumeric(5)]: faker.number.float({
        min: undefined,
        max: undefined,
        fractionDigits: 2,
      }),
    },
    undefined,
  ]),
  quantityPerItem: faker.helpers.arrayElement([
    faker.number.float({ min: undefined, max: undefined, fractionDigits: 2 }),
    undefined,
  ]),
  itemPerBundle: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  tags: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => faker.string.alpha({ length: { min: 10, max: 20 } })),
    undefined,
  ]),
  ...overrideResponse,
});

export const getGetApiProductSearchResponseMock = (): ProductInfo[] =>
  Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.helpers.arrayElement([
      faker.number.int({ min: undefined, max: undefined }),
      undefined,
    ]),
    name: faker.string.alpha({ length: { min: 1, max: 20 } }),
    imgUrl: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    desc: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    gtin: faker.helpers.arrayElement([
      faker.helpers.fromRegExp("^([0-9]{8}|[0-9]{12,14})$"),
      undefined,
    ]),
    unit: faker.helpers.arrayElement(Object.values(Unit)),
    latestQuotes: faker.helpers.arrayElement([
      Array.from(
        { length: faker.number.int({ min: 1, max: 10 }) },
        (_, i) => i + 1,
      ).map(() => ({
        productName: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        productImgPath: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        productId: faker.helpers.arrayElement([
          faker.number.int({ min: undefined, max: undefined }),
          undefined,
        ]),
        storeInfo: faker.helpers.arrayElement([
          {
            id: faker.helpers.arrayElement([
              faker.number.int({ min: undefined, max: undefined }),
              undefined,
            ]),
            name: faker.string.alpha({ length: { min: 10, max: 20 } }),
            address: faker.helpers.arrayElement([
              faker.string.alpha({ length: { min: 10, max: 20 } }),
              undefined,
            ]),
            storeGroupLogoPath: faker.helpers.arrayElement([
              faker.string.alpha({ length: { min: 10, max: 20 } }),
              undefined,
            ]),
            url: faker.helpers.arrayElement([
              faker.string.alpha({ length: { min: 10, max: 20 } }),
              undefined,
            ]),
          },
          undefined,
        ]),
        quoteDate: faker.date.past().toISOString().split("T")[0],
        price: faker.number.float({
          min: undefined,
          max: undefined,
          fractionDigits: 2,
        }),
        unitScale: faker.helpers.arrayElement([
          faker.number.float({
            min: undefined,
            max: undefined,
            fractionDigits: 2,
          }),
          undefined,
        ]),
        unitPrice: faker.number.float({
          min: undefined,
          max: undefined,
          fractionDigits: 2,
        }),
        unit: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        discountType: faker.helpers.arrayElement([
          faker.helpers.arrayElement(Object.values(Type)),
          undefined,
        ]),
        discountPrice: faker.helpers.arrayElement([
          faker.number.float({
            min: undefined,
            max: undefined,
            fractionDigits: 2,
          }),
          undefined,
        ]),
        multibuyQuantity: faker.helpers.arrayElement([
          faker.number.float({
            min: undefined,
            max: undefined,
            fractionDigits: 2,
          }),
          undefined,
        ]),
      })),
      undefined,
    ]),
    stats: faker.helpers.arrayElement([
      {
        [faker.string.alphanumeric(5)]: faker.number.float({
          min: undefined,
          max: undefined,
          fractionDigits: 2,
        }),
      },
      undefined,
    ]),
    quantityPerItem: faker.helpers.arrayElement([
      faker.number.float({ min: undefined, max: undefined, fractionDigits: 2 }),
      undefined,
    ]),
    itemPerBundle: faker.helpers.arrayElement([
      faker.number.int({ min: undefined, max: undefined }),
      undefined,
    ]),
    tags: faker.helpers.arrayElement([
      Array.from(
        { length: faker.number.int({ min: 1, max: 10 }) },
        (_, i) => i + 1,
      ).map(() => faker.string.alpha({ length: { min: 10, max: 20 } })),
      undefined,
    ]),
  }));

export const getPostApiProductSearchExtResponseMock = (): QuoteDTO[] =>
  Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    productInfo: faker.helpers.arrayElement([
      {
        id: faker.helpers.arrayElement([
          faker.number.int({ min: undefined, max: undefined }),
          undefined,
        ]),
        name: faker.string.alpha({ length: { min: 1, max: 20 } }),
        imgUrl: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        desc: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        gtin: faker.helpers.arrayElement([
          faker.helpers.fromRegExp("^([0-9]{8}|[0-9]{12,14})$"),
          undefined,
        ]),
        unit: faker.helpers.arrayElement(Object.values(Unit)),
        latestQuotes: faker.helpers.arrayElement([
          Array.from(
            { length: faker.number.int({ min: 1, max: 10 }) },
            (_, i) => i + 1,
          ).map(() => ({
            productName: faker.helpers.arrayElement([
              faker.string.alpha({ length: { min: 10, max: 20 } }),
              undefined,
            ]),
            productImgPath: faker.helpers.arrayElement([
              faker.string.alpha({ length: { min: 10, max: 20 } }),
              undefined,
            ]),
            productId: faker.helpers.arrayElement([
              faker.number.int({ min: undefined, max: undefined }),
              undefined,
            ]),
            storeInfo: faker.helpers.arrayElement([
              {
                id: faker.helpers.arrayElement([
                  faker.number.int({ min: undefined, max: undefined }),
                  undefined,
                ]),
                name: faker.string.alpha({ length: { min: 10, max: 20 } }),
                address: faker.helpers.arrayElement([
                  faker.string.alpha({ length: { min: 10, max: 20 } }),
                  undefined,
                ]),
                storeGroupLogoPath: faker.helpers.arrayElement([
                  faker.string.alpha({ length: { min: 10, max: 20 } }),
                  undefined,
                ]),
                url: faker.helpers.arrayElement([
                  faker.string.alpha({ length: { min: 10, max: 20 } }),
                  undefined,
                ]),
              },
              undefined,
            ]),
            quoteDate: faker.date.past().toISOString().split("T")[0],
            price: faker.number.float({
              min: undefined,
              max: undefined,
              fractionDigits: 2,
            }),
            unitScale: faker.helpers.arrayElement([
              faker.number.float({
                min: undefined,
                max: undefined,
                fractionDigits: 2,
              }),
              undefined,
            ]),
            unitPrice: faker.number.float({
              min: undefined,
              max: undefined,
              fractionDigits: 2,
            }),
            unit: faker.helpers.arrayElement([
              faker.string.alpha({ length: { min: 10, max: 20 } }),
              undefined,
            ]),
            discountType: faker.helpers.arrayElement([
              faker.helpers.arrayElement(Object.values(Type)),
              undefined,
            ]),
            discountPrice: faker.helpers.arrayElement([
              faker.number.float({
                min: undefined,
                max: undefined,
                fractionDigits: 2,
              }),
              undefined,
            ]),
            multibuyQuantity: faker.helpers.arrayElement([
              faker.number.float({
                min: undefined,
                max: undefined,
                fractionDigits: 2,
              }),
              undefined,
            ]),
          })),
          undefined,
        ]),
        stats: faker.helpers.arrayElement([
          {
            [faker.string.alphanumeric(5)]: faker.number.float({
              min: undefined,
              max: undefined,
              fractionDigits: 2,
            }),
          },
          undefined,
        ]),
        quantityPerItem: faker.helpers.arrayElement([
          faker.number.float({
            min: undefined,
            max: undefined,
            fractionDigits: 2,
          }),
          undefined,
        ]),
        itemPerBundle: faker.helpers.arrayElement([
          faker.number.int({ min: undefined, max: undefined }),
          undefined,
        ]),
        tags: faker.helpers.arrayElement([
          Array.from(
            { length: faker.number.int({ min: 1, max: 10 }) },
            (_, i) => i + 1,
          ).map(() => faker.string.alpha({ length: { min: 10, max: 20 } })),
          undefined,
        ]),
      },
      undefined,
    ]),
    storeInfo: faker.helpers.arrayElement([
      {
        id: faker.helpers.arrayElement([
          faker.number.int({ min: undefined, max: undefined }),
          undefined,
        ]),
        name: faker.string.alpha({ length: { min: 10, max: 20 } }),
        address: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        storeGroupLogoPath: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        url: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
      },
      { id: faker.number.int({ min: undefined, max: undefined }) },
    ]),
    quoteDate: faker.date.past().toISOString().split("T")[0],
    price: faker.number.float({
      min: undefined,
      max: undefined,
      fractionDigits: 2,
    }),
    discountType: faker.helpers.arrayElement([
      faker.helpers.arrayElement(Object.values(Type)),
      undefined,
    ]),
    discountPrice: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        faker.number.float({
          min: undefined,
          max: undefined,
          fractionDigits: 2,
        }),
        null,
      ]),
      undefined,
    ]),
    multibuyQuantity: faker.helpers.arrayElement([
      faker.number.int({ min: undefined, max: undefined }),
      undefined,
    ]),
  }));

export const getGetApiProductSuggestResponseMock = (): string[] =>
  Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, () =>
    faker.word.sample(),
  );

export const getGetApiProductProductIdResponseMock = (
  overrideResponse: Partial<ProductInfo> = {},
): ProductInfo => ({
  id: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  name: faker.string.alpha({ length: { min: 1, max: 20 } }),
  imgUrl: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  desc: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  gtin: faker.helpers.arrayElement([
    faker.helpers.fromRegExp("^([0-9]{8}|[0-9]{12,14})$"),
    undefined,
  ]),
  unit: faker.helpers.arrayElement(Object.values(Unit)),
  latestQuotes: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      productName: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      productImgPath: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      productId: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      storeInfo: faker.helpers.arrayElement([
        {
          id: faker.helpers.arrayElement([
            faker.number.int({ min: undefined, max: undefined }),
            undefined,
          ]),
          name: faker.string.alpha({ length: { min: 10, max: 20 } }),
          address: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
          ]),
          storeGroupLogoPath: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
          ]),
          url: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
          ]),
        },
        undefined,
      ]),
      quoteDate: faker.date.past().toISOString().split("T")[0],
      price: faker.number.float({
        min: undefined,
        max: undefined,
        fractionDigits: 2,
      }),
      unitScale: faker.helpers.arrayElement([
        faker.number.float({
          min: undefined,
          max: undefined,
          fractionDigits: 2,
        }),
        undefined,
      ]),
      unitPrice: faker.number.float({
        min: undefined,
        max: undefined,
        fractionDigits: 2,
      }),
      unit: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      discountType: faker.helpers.arrayElement([
        faker.helpers.arrayElement(Object.values(Type)),
        undefined,
      ]),
      discountPrice: faker.helpers.arrayElement([
        faker.number.float({
          min: undefined,
          max: undefined,
          fractionDigits: 2,
        }),
        undefined,
      ]),
      multibuyQuantity: faker.helpers.arrayElement([
        faker.number.float({
          min: undefined,
          max: undefined,
          fractionDigits: 2,
        }),
        undefined,
      ]),
    })),
    undefined,
  ]),
  stats: faker.helpers.arrayElement([
    {
      [faker.string.alphanumeric(5)]: faker.number.float({
        min: undefined,
        max: undefined,
        fractionDigits: 2,
      }),
    },
    undefined,
  ]),
  quantityPerItem: faker.helpers.arrayElement([
    faker.number.float({ min: undefined, max: undefined, fractionDigits: 2 }),
    undefined,
  ]),
  itemPerBundle: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  tags: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => faker.string.alpha({ length: { min: 10, max: 20 } })),
    undefined,
  ]),
  ...overrideResponse,
});

export const getGetApiProductProductIdGetAlertResponseMock = (
  overrideResponse: Partial<AlertDTO> = {},
): AlertDTO => ({
  productId: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  priceLevel: faker.helpers.arrayElement([
    faker.number.float({ min: undefined, max: undefined, fractionDigits: 2 }),
    undefined,
  ]),
  ...overrideResponse,
});

export const getPostApiProductProductIdQuoteResponseMock = (
  overrideResponse: Partial<QuoteDTO> = {},
): QuoteDTO => ({
  productInfo: faker.helpers.arrayElement([
    {
      id: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      name: faker.string.alpha({ length: { min: 1, max: 20 } }),
      imgUrl: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      desc: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      gtin: faker.helpers.arrayElement([
        faker.helpers.fromRegExp("^([0-9]{8}|[0-9]{12,14})$"),
        undefined,
      ]),
      unit: faker.helpers.arrayElement(Object.values(Unit)),
      latestQuotes: faker.helpers.arrayElement([
        Array.from(
          { length: faker.number.int({ min: 1, max: 10 }) },
          (_, i) => i + 1,
        ).map(() => ({
          productName: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
          ]),
          productImgPath: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
          ]),
          productId: faker.helpers.arrayElement([
            faker.number.int({ min: undefined, max: undefined }),
            undefined,
          ]),
          storeInfo: faker.helpers.arrayElement([
            {
              id: faker.helpers.arrayElement([
                faker.number.int({ min: undefined, max: undefined }),
                undefined,
              ]),
              name: faker.string.alpha({ length: { min: 10, max: 20 } }),
              address: faker.helpers.arrayElement([
                faker.string.alpha({ length: { min: 10, max: 20 } }),
                undefined,
              ]),
              storeGroupLogoPath: faker.helpers.arrayElement([
                faker.string.alpha({ length: { min: 10, max: 20 } }),
                undefined,
              ]),
              url: faker.helpers.arrayElement([
                faker.string.alpha({ length: { min: 10, max: 20 } }),
                undefined,
              ]),
            },
            undefined,
          ]),
          quoteDate: faker.date.past().toISOString().split("T")[0],
          price: faker.number.float({
            min: undefined,
            max: undefined,
            fractionDigits: 2,
          }),
          unitScale: faker.helpers.arrayElement([
            faker.number.float({
              min: undefined,
              max: undefined,
              fractionDigits: 2,
            }),
            undefined,
          ]),
          unitPrice: faker.number.float({
            min: undefined,
            max: undefined,
            fractionDigits: 2,
          }),
          unit: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
          ]),
          discountType: faker.helpers.arrayElement([
            faker.helpers.arrayElement(Object.values(Type)),
            undefined,
          ]),
          discountPrice: faker.helpers.arrayElement([
            faker.number.float({
              min: undefined,
              max: undefined,
              fractionDigits: 2,
            }),
            undefined,
          ]),
          multibuyQuantity: faker.helpers.arrayElement([
            faker.number.float({
              min: undefined,
              max: undefined,
              fractionDigits: 2,
            }),
            undefined,
          ]),
        })),
        undefined,
      ]),
      stats: faker.helpers.arrayElement([
        {
          [faker.string.alphanumeric(5)]: faker.number.float({
            min: undefined,
            max: undefined,
            fractionDigits: 2,
          }),
        },
        undefined,
      ]),
      quantityPerItem: faker.helpers.arrayElement([
        faker.number.float({
          min: undefined,
          max: undefined,
          fractionDigits: 2,
        }),
        undefined,
      ]),
      itemPerBundle: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      tags: faker.helpers.arrayElement([
        Array.from(
          { length: faker.number.int({ min: 1, max: 10 }) },
          (_, i) => i + 1,
        ).map(() => faker.string.alpha({ length: { min: 10, max: 20 } })),
        undefined,
      ]),
    },
    undefined,
  ]),
  storeInfo: faker.helpers.arrayElement([
    {
      id: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      name: faker.string.alpha({ length: { min: 10, max: 20 } }),
      address: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      storeGroupLogoPath: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      url: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
    },
    { id: faker.number.int({ min: undefined, max: undefined }) },
  ]),
  quoteDate: faker.date.past().toISOString().split("T")[0],
  price: faker.number.float({
    min: undefined,
    max: undefined,
    fractionDigits: 2,
  }),
  discountType: faker.helpers.arrayElement([
    faker.helpers.arrayElement(Object.values(Type)),
    undefined,
  ]),
  discountPrice: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.number.float({ min: undefined, max: undefined, fractionDigits: 2 }),
      null,
    ]),
    undefined,
  ]),
  multibuyQuantity: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  ...overrideResponse,
});

export const getGetApiProductProductIdQuoteHistResponseMock = (): QuoteDTO[] =>
  Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    productInfo: faker.helpers.arrayElement([
      {
        id: faker.helpers.arrayElement([
          faker.number.int({ min: undefined, max: undefined }),
          undefined,
        ]),
        name: faker.string.alpha({ length: { min: 1, max: 20 } }),
        imgUrl: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        desc: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        gtin: faker.helpers.arrayElement([
          faker.helpers.fromRegExp("^([0-9]{8}|[0-9]{12,14})$"),
          undefined,
        ]),
        unit: faker.helpers.arrayElement(Object.values(Unit)),
        latestQuotes: faker.helpers.arrayElement([
          Array.from(
            { length: faker.number.int({ min: 1, max: 10 }) },
            (_, i) => i + 1,
          ).map(() => ({
            productName: faker.helpers.arrayElement([
              faker.string.alpha({ length: { min: 10, max: 20 } }),
              undefined,
            ]),
            productImgPath: faker.helpers.arrayElement([
              faker.string.alpha({ length: { min: 10, max: 20 } }),
              undefined,
            ]),
            productId: faker.helpers.arrayElement([
              faker.number.int({ min: undefined, max: undefined }),
              undefined,
            ]),
            storeInfo: faker.helpers.arrayElement([
              {
                id: faker.helpers.arrayElement([
                  faker.number.int({ min: undefined, max: undefined }),
                  undefined,
                ]),
                name: faker.string.alpha({ length: { min: 10, max: 20 } }),
                address: faker.helpers.arrayElement([
                  faker.string.alpha({ length: { min: 10, max: 20 } }),
                  undefined,
                ]),
                storeGroupLogoPath: faker.helpers.arrayElement([
                  faker.string.alpha({ length: { min: 10, max: 20 } }),
                  undefined,
                ]),
                url: faker.helpers.arrayElement([
                  faker.string.alpha({ length: { min: 10, max: 20 } }),
                  undefined,
                ]),
              },
              undefined,
            ]),
            quoteDate: faker.date.past().toISOString().split("T")[0],
            price: faker.number.float({
              min: undefined,
              max: undefined,
              fractionDigits: 2,
            }),
            unitScale: faker.helpers.arrayElement([
              faker.number.float({
                min: undefined,
                max: undefined,
                fractionDigits: 2,
              }),
              undefined,
            ]),
            unitPrice: faker.number.float({
              min: undefined,
              max: undefined,
              fractionDigits: 2,
            }),
            unit: faker.helpers.arrayElement([
              faker.string.alpha({ length: { min: 10, max: 20 } }),
              undefined,
            ]),
            discountType: faker.helpers.arrayElement([
              faker.helpers.arrayElement(Object.values(Type)),
              undefined,
            ]),
            discountPrice: faker.helpers.arrayElement([
              faker.number.float({
                min: undefined,
                max: undefined,
                fractionDigits: 2,
              }),
              undefined,
            ]),
            multibuyQuantity: faker.helpers.arrayElement([
              faker.number.float({
                min: undefined,
                max: undefined,
                fractionDigits: 2,
              }),
              undefined,
            ]),
          })),
          undefined,
        ]),
        stats: faker.helpers.arrayElement([
          {
            [faker.string.alphanumeric(5)]: faker.number.float({
              min: undefined,
              max: undefined,
              fractionDigits: 2,
            }),
          },
          undefined,
        ]),
        quantityPerItem: faker.helpers.arrayElement([
          faker.number.float({
            min: undefined,
            max: undefined,
            fractionDigits: 2,
          }),
          undefined,
        ]),
        itemPerBundle: faker.helpers.arrayElement([
          faker.number.int({ min: undefined, max: undefined }),
          undefined,
        ]),
        tags: faker.helpers.arrayElement([
          Array.from(
            { length: faker.number.int({ min: 1, max: 10 }) },
            (_, i) => i + 1,
          ).map(() => faker.string.alpha({ length: { min: 10, max: 20 } })),
          undefined,
        ]),
      },
      undefined,
    ]),
    storeInfo: faker.helpers.arrayElement([
      {
        id: faker.helpers.arrayElement([
          faker.number.int({ min: undefined, max: undefined }),
          undefined,
        ]),
        name: faker.string.alpha({ length: { min: 10, max: 20 } }),
        address: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        storeGroupLogoPath: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        url: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
      },
      { id: faker.number.int({ min: undefined, max: undefined }) },
    ]),
    quoteDate: faker.date.past().toISOString().split("T")[0],
    price: faker.number.float({
      min: undefined,
      max: undefined,
      fractionDigits: 2,
    }),
    discountType: faker.helpers.arrayElement([
      faker.helpers.arrayElement(Object.values(Type)),
      undefined,
    ]),
    discountPrice: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        faker.number.float({
          min: undefined,
          max: undefined,
          fractionDigits: 2,
        }),
        null,
      ]),
      undefined,
    ]),
    multibuyQuantity: faker.helpers.arrayElement([
      faker.number.int({ min: undefined, max: undefined }),
      undefined,
    ]),
  }));

export const getGetApiAdminBatchAllMockHandler = (
  overrideResponse?:
    | JobInfo[]
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<JobInfo[]> | JobInfo[]),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/admin/batch/all",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getGetApiAdminBatchAllResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getPostApiAdminBatchDisableMockHandler = (
  overrideResponse?:
    | unknown
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<unknown> | unknown),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/api/admin/batch/disable",
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};

export const getPostApiAdminBatchEnableMockHandler = (
  overrideResponse?:
    | unknown
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<unknown> | unknown),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/api/admin/batch/enable",
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};

export const getPostApiAdminBatchNewProductQuoteImportMockHandler = (
  overrideResponse?:
    | unknown
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<unknown> | unknown),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/api/admin/batch/newProductQuoteImport",
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};

export const getPostApiAdminBatchNewStoreImportMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/api/admin/batch/newStoreImport",
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 201 });
    },
    options,
  );
};

export const getPostApiAdminBatchBatchIdRunMockHandler = (
  overrideResponse?:
    | unknown
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<unknown> | unknown),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/api/admin/batch/:batchId/run",
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};

export const getPostApiAdminStoreNewMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/api/admin/store/new",
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 201 });
    },
    options,
  );
};

export const getGetApiAdminStoreSearchMockHandler = (
  overrideResponse?:
    | StoreInfo[]
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<StoreInfo[]> | StoreInfo[]),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/admin/store/search",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getGetApiAdminStoreSearchResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getGetApiCommonLatestDealsMockHandler = (
  overrideResponse?:
    | QuoteResult
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<QuoteResult> | QuoteResult),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/common/latestDeals",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getGetApiCommonLatestDealsResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getGetApiProductAlertsMockHandler = (
  overrideResponse?:
    | SimpleQuoteDTO[]
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<SimpleQuoteDTO[]> | SimpleQuoteDTO[]),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/product/alerts",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getGetApiProductAlertsResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getGetApiProductAllMockHandler = (
  overrideResponse?:
    | ProductResult
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ProductResult> | ProductResult),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/product/all",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getGetApiProductAllResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getGetApiProductExtSourcesMockHandler = (
  overrideResponse?:
    | string[]
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<string[]> | string[]),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/product/extSources",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getGetApiProductExtSourcesResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getGetApiProductGtinGtinMockHandler = (
  overrideResponse?:
    | ProductInfo
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ProductInfo> | ProductInfo),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/product/gtin/:gtin",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getGetApiProductGtinGtinResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getPostApiProductNewMockHandler = (
  overrideResponse?:
    | ProductInfo
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ProductInfo> | ProductInfo),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/api/product/new",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getPostApiProductNewResponseMock(),
        ),
        { status: 201, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getGetApiProductSearchMockHandler = (
  overrideResponse?:
    | ProductInfo[]
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ProductInfo[]> | ProductInfo[]),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/product/search",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getGetApiProductSearchResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getPostApiProductSearchExtMockHandler = (
  overrideResponse?:
    | QuoteDTO[]
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<QuoteDTO[]> | QuoteDTO[]),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/api/product/searchExt",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getPostApiProductSearchExtResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getGetApiProductSuggestMockHandler = (
  overrideResponse?:
    | string[]
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<string[]> | string[]),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/product/suggest",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getGetApiProductSuggestResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getGetApiProductProductIdMockHandler = (
  overrideResponse?:
    | ProductInfo
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ProductInfo> | ProductInfo),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/product/:productId",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getGetApiProductProductIdResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getPostApiProductProductIdEditMockHandler = (
  overrideResponse?:
    | unknown
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<unknown> | unknown),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/api/product/:productId/edit",
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};

export const getPostApiProductProductIdEditAlertMockHandler = (
  overrideResponse?:
    | unknown
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<unknown> | unknown),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/api/product/:productId/editAlert",
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};

export const getGetApiProductProductIdGetAlertMockHandler = (
  overrideResponse?:
    | AlertDTO
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<AlertDTO> | AlertDTO),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/product/:productId/getAlert",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getGetApiProductProductIdGetAlertResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getPostApiProductProductIdQuoteMockHandler = (
  overrideResponse?:
    | QuoteDTO
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<QuoteDTO> | QuoteDTO),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/api/product/:productId/quote",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getPostApiProductProductIdQuoteResponseMock(),
        ),
        { status: 202, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getGetApiProductProductIdQuoteHistMockHandler = (
  overrideResponse?:
    | QuoteDTO[]
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<QuoteDTO[]> | QuoteDTO[]),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/product/:productId/quoteHist",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getGetApiProductProductIdQuoteHistResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};
export const getPricekeepAPIMock = () => [
  getGetApiAdminBatchAllMockHandler(),
  getPostApiAdminBatchDisableMockHandler(),
  getPostApiAdminBatchEnableMockHandler(),
  getPostApiAdminBatchNewProductQuoteImportMockHandler(),
  getPostApiAdminBatchNewStoreImportMockHandler(),
  getPostApiAdminBatchBatchIdRunMockHandler(),
  getPostApiAdminStoreNewMockHandler(),
  getGetApiAdminStoreSearchMockHandler(),
  getGetApiCommonLatestDealsMockHandler(),
  getGetApiProductAlertsMockHandler(),
  getGetApiProductAllMockHandler(),
  getGetApiProductExtSourcesMockHandler(),
  getGetApiProductGtinGtinMockHandler(),
  getPostApiProductNewMockHandler(),
  getGetApiProductSearchMockHandler(),
  getPostApiProductSearchExtMockHandler(),
  getGetApiProductSuggestMockHandler(),
  getGetApiProductProductIdMockHandler(),
  getPostApiProductProductIdEditMockHandler(),
  getPostApiProductProductIdEditAlertMockHandler(),
  getGetApiProductProductIdGetAlertMockHandler(),
  getPostApiProductProductIdQuoteMockHandler(),
  getGetApiProductProductIdQuoteHistMockHandler(),
];
