/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import { faker } from "@faker-js/faker";

import { HttpResponse, delay, http } from "msw";
import type { RequestHandlerOptions } from "msw";

import { Type, Unit } from "./model";
import type { ChartNode, ProductInfo, QuoteDTO, QuoteResult } from "./model";

export const getGetApiCommonLatestDealsResponseMock = (
  overrideResponse: Partial<QuoteResult> = {},
): QuoteResult => ({
  results: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      id: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      productInfo: faker.helpers.arrayElement([
        {
          id: faker.helpers.arrayElement([
            faker.number.int({ min: undefined, max: undefined }),
            undefined,
          ]),
          name: faker.string.alpha({ length: { min: 1, max: 20 } }),
          imgUrl: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
          ]),
          desc: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
          ]),
          gtin: faker.helpers.arrayElement([
            faker.helpers.fromRegExp(
              "^([0-9]d{8}|[0-9]{12}|[0-9]{13}|[0-9]{14})$",
            ),
            undefined,
          ]),
          unit: faker.helpers.arrayElement(Object.values(Unit)),
          latestQuotes: faker.helpers.arrayElement([
            Array.from(
              { length: faker.number.int({ min: 1, max: 10 }) },
              (_, i) => i + 1,
            ).map(() => ({
              id: faker.helpers.arrayElement([
                faker.number.int({ min: undefined, max: undefined }),
                undefined,
              ]),
              storeInfo: faker.helpers.arrayElement([
                {
                  id: faker.helpers.arrayElement([
                    faker.number.int({ min: undefined, max: undefined }),
                    undefined,
                  ]),
                  name: faker.string.alpha({ length: { min: 10, max: 20 } }),
                  address: faker.helpers.arrayElement([
                    faker.string.alpha({ length: { min: 10, max: 20 } }),
                    undefined,
                  ]),
                  url: faker.helpers.arrayElement([
                    faker.string.alpha({ length: { min: 10, max: 20 } }),
                    undefined,
                  ]),
                },
                undefined,
              ]),
              quoteDate: faker.date.past().toISOString().split("T")[0],
              price: faker.number.float({
                min: undefined,
                max: undefined,
                fractionDigits: 2,
              }),
              discountType: faker.helpers.arrayElement([
                faker.helpers.arrayElement(Object.values(Type)),
                undefined,
              ]),
            })),
            undefined,
          ]),
          stats: faker.helpers.arrayElement([
            {
              [faker.string.alphanumeric(5)]: faker.number.float({
                min: undefined,
                max: undefined,
                fractionDigits: 2,
              }),
            },
            undefined,
          ]),
          quantityPerItem: faker.helpers.arrayElement([
            faker.number.float({
              min: undefined,
              max: undefined,
              fractionDigits: 2,
            }),
            undefined,
          ]),
          itemPerBundle: faker.helpers.arrayElement([
            faker.number.int({ min: undefined, max: undefined }),
            undefined,
          ]),
          tags: faker.helpers.arrayElement([
            Array.from(
              { length: faker.number.int({ min: 1, max: 10 }) },
              (_, i) => i + 1,
            ).map(() => faker.string.alpha({ length: { min: 10, max: 20 } })),
            undefined,
          ]),
        },
        undefined,
      ]),
      storeInfo: faker.helpers.arrayElement([
        {
          id: faker.helpers.arrayElement([
            faker.number.int({ min: undefined, max: undefined }),
            undefined,
          ]),
          name: faker.string.alpha({ length: { min: 10, max: 20 } }),
          address: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
          ]),
          url: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
          ]),
        },
        { id: faker.number.int({ min: undefined, max: undefined }) },
      ]),
      quoteDate: faker.date.past().toISOString().split("T")[0],
      price: faker.number.float({
        min: undefined,
        max: undefined,
        fractionDigits: 2,
      }),
      discountType: faker.helpers.arrayElement([
        faker.helpers.arrayElement(Object.values(Type)),
        undefined,
      ]),
    })),
    undefined,
  ]),
  ...overrideResponse,
});

export const getGetApiProductAlertsResponseMock = (): QuoteDTO[] =>
  Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.helpers.arrayElement([
      faker.number.int({ min: undefined, max: undefined }),
      undefined,
    ]),
    productInfo: faker.helpers.arrayElement([
      {
        id: faker.helpers.arrayElement([
          faker.number.int({ min: undefined, max: undefined }),
          undefined,
        ]),
        name: faker.string.alpha({ length: { min: 1, max: 20 } }),
        imgUrl: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        desc: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        gtin: faker.helpers.arrayElement([
          faker.helpers.fromRegExp(
            "^([0-9]d{8}|[0-9]{12}|[0-9]{13}|[0-9]{14})$",
          ),
          undefined,
        ]),
        unit: faker.helpers.arrayElement(Object.values(Unit)),
        latestQuotes: faker.helpers.arrayElement([
          Array.from(
            { length: faker.number.int({ min: 1, max: 10 }) },
            (_, i) => i + 1,
          ).map(() => ({
            id: faker.helpers.arrayElement([
              faker.number.int({ min: undefined, max: undefined }),
              undefined,
            ]),
            storeInfo: faker.helpers.arrayElement([
              {
                id: faker.helpers.arrayElement([
                  faker.number.int({ min: undefined, max: undefined }),
                  undefined,
                ]),
                name: faker.string.alpha({ length: { min: 10, max: 20 } }),
                address: faker.helpers.arrayElement([
                  faker.string.alpha({ length: { min: 10, max: 20 } }),
                  undefined,
                ]),
                url: faker.helpers.arrayElement([
                  faker.string.alpha({ length: { min: 10, max: 20 } }),
                  undefined,
                ]),
              },
              undefined,
            ]),
            quoteDate: faker.date.past().toISOString().split("T")[0],
            price: faker.number.float({
              min: undefined,
              max: undefined,
              fractionDigits: 2,
            }),
            discountType: faker.helpers.arrayElement([
              faker.helpers.arrayElement(Object.values(Type)),
              undefined,
            ]),
          })),
          undefined,
        ]),
        stats: faker.helpers.arrayElement([
          {
            [faker.string.alphanumeric(5)]: faker.number.float({
              min: undefined,
              max: undefined,
              fractionDigits: 2,
            }),
          },
          undefined,
        ]),
        quantityPerItem: faker.helpers.arrayElement([
          faker.number.float({
            min: undefined,
            max: undefined,
            fractionDigits: 2,
          }),
          undefined,
        ]),
        itemPerBundle: faker.helpers.arrayElement([
          faker.number.int({ min: undefined, max: undefined }),
          undefined,
        ]),
        tags: faker.helpers.arrayElement([
          Array.from(
            { length: faker.number.int({ min: 1, max: 10 }) },
            (_, i) => i + 1,
          ).map(() => faker.string.alpha({ length: { min: 10, max: 20 } })),
          undefined,
        ]),
      },
      undefined,
    ]),
    storeInfo: faker.helpers.arrayElement([
      {
        id: faker.helpers.arrayElement([
          faker.number.int({ min: undefined, max: undefined }),
          undefined,
        ]),
        name: faker.string.alpha({ length: { min: 10, max: 20 } }),
        address: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        url: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
      },
      { id: faker.number.int({ min: undefined, max: undefined }) },
    ]),
    quoteDate: faker.date.past().toISOString().split("T")[0],
    price: faker.number.float({
      min: undefined,
      max: undefined,
      fractionDigits: 2,
    }),
    discountType: faker.helpers.arrayElement([
      faker.helpers.arrayElement(Object.values(Type)),
      undefined,
    ]),
  }));

export const getGetApiProductExtSourcesResponseMock = (): string[] =>
  Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, () =>
    faker.word.sample(),
  );

export const getGetApiProductGtinGtinResponseMock = (
  overrideResponse: Partial<ProductInfo> = {},
): ProductInfo => ({
  id: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  name: faker.string.alpha({ length: { min: 1, max: 20 } }),
  imgUrl: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  desc: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  gtin: faker.helpers.arrayElement([
    faker.helpers.fromRegExp("^([0-9]d{8}|[0-9]{12}|[0-9]{13}|[0-9]{14})$"),
    undefined,
  ]),
  unit: faker.helpers.arrayElement(Object.values(Unit)),
  latestQuotes: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      id: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      storeInfo: faker.helpers.arrayElement([
        {
          id: faker.helpers.arrayElement([
            faker.number.int({ min: undefined, max: undefined }),
            undefined,
          ]),
          name: faker.string.alpha({ length: { min: 10, max: 20 } }),
          address: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
          ]),
          url: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
          ]),
        },
        undefined,
      ]),
      quoteDate: faker.date.past().toISOString().split("T")[0],
      price: faker.number.float({
        min: undefined,
        max: undefined,
        fractionDigits: 2,
      }),
      discountType: faker.helpers.arrayElement([
        faker.helpers.arrayElement(Object.values(Type)),
        undefined,
      ]),
    })),
    undefined,
  ]),
  stats: faker.helpers.arrayElement([
    {
      [faker.string.alphanumeric(5)]: faker.number.float({
        min: undefined,
        max: undefined,
        fractionDigits: 2,
      }),
    },
    undefined,
  ]),
  quantityPerItem: faker.helpers.arrayElement([
    faker.number.float({ min: undefined, max: undefined, fractionDigits: 2 }),
    undefined,
  ]),
  itemPerBundle: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  tags: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => faker.string.alpha({ length: { min: 10, max: 20 } })),
    undefined,
  ]),
  ...overrideResponse,
});

export const getGetApiProductSearchResponseMock = (): ProductInfo[] =>
  Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.helpers.arrayElement([
      faker.number.int({ min: undefined, max: undefined }),
      undefined,
    ]),
    name: faker.string.alpha({ length: { min: 1, max: 20 } }),
    imgUrl: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    desc: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    gtin: faker.helpers.arrayElement([
      faker.helpers.fromRegExp("^([0-9]d{8}|[0-9]{12}|[0-9]{13}|[0-9]{14})$"),
      undefined,
    ]),
    unit: faker.helpers.arrayElement(Object.values(Unit)),
    latestQuotes: faker.helpers.arrayElement([
      Array.from(
        { length: faker.number.int({ min: 1, max: 10 }) },
        (_, i) => i + 1,
      ).map(() => ({
        id: faker.helpers.arrayElement([
          faker.number.int({ min: undefined, max: undefined }),
          undefined,
        ]),
        storeInfo: faker.helpers.arrayElement([
          {
            id: faker.helpers.arrayElement([
              faker.number.int({ min: undefined, max: undefined }),
              undefined,
            ]),
            name: faker.string.alpha({ length: { min: 10, max: 20 } }),
            address: faker.helpers.arrayElement([
              faker.string.alpha({ length: { min: 10, max: 20 } }),
              undefined,
            ]),
            url: faker.helpers.arrayElement([
              faker.string.alpha({ length: { min: 10, max: 20 } }),
              undefined,
            ]),
          },
          undefined,
        ]),
        quoteDate: faker.date.past().toISOString().split("T")[0],
        price: faker.number.float({
          min: undefined,
          max: undefined,
          fractionDigits: 2,
        }),
        discountType: faker.helpers.arrayElement([
          faker.helpers.arrayElement(Object.values(Type)),
          undefined,
        ]),
      })),
      undefined,
    ]),
    stats: faker.helpers.arrayElement([
      {
        [faker.string.alphanumeric(5)]: faker.number.float({
          min: undefined,
          max: undefined,
          fractionDigits: 2,
        }),
      },
      undefined,
    ]),
    quantityPerItem: faker.helpers.arrayElement([
      faker.number.float({ min: undefined, max: undefined, fractionDigits: 2 }),
      undefined,
    ]),
    itemPerBundle: faker.helpers.arrayElement([
      faker.number.int({ min: undefined, max: undefined }),
      undefined,
    ]),
    tags: faker.helpers.arrayElement([
      Array.from(
        { length: faker.number.int({ min: 1, max: 10 }) },
        (_, i) => i + 1,
      ).map(() => faker.string.alpha({ length: { min: 10, max: 20 } })),
      undefined,
    ]),
  }));

export const getPostApiProductSearchExtResponseMock = (): QuoteDTO[] =>
  Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.helpers.arrayElement([
      faker.number.int({ min: undefined, max: undefined }),
      undefined,
    ]),
    productInfo: faker.helpers.arrayElement([
      {
        id: faker.helpers.arrayElement([
          faker.number.int({ min: undefined, max: undefined }),
          undefined,
        ]),
        name: faker.string.alpha({ length: { min: 1, max: 20 } }),
        imgUrl: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        desc: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        gtin: faker.helpers.arrayElement([
          faker.helpers.fromRegExp(
            "^([0-9]d{8}|[0-9]{12}|[0-9]{13}|[0-9]{14})$",
          ),
          undefined,
        ]),
        unit: faker.helpers.arrayElement(Object.values(Unit)),
        latestQuotes: faker.helpers.arrayElement([
          Array.from(
            { length: faker.number.int({ min: 1, max: 10 }) },
            (_, i) => i + 1,
          ).map(() => ({
            id: faker.helpers.arrayElement([
              faker.number.int({ min: undefined, max: undefined }),
              undefined,
            ]),
            storeInfo: faker.helpers.arrayElement([
              {
                id: faker.helpers.arrayElement([
                  faker.number.int({ min: undefined, max: undefined }),
                  undefined,
                ]),
                name: faker.string.alpha({ length: { min: 10, max: 20 } }),
                address: faker.helpers.arrayElement([
                  faker.string.alpha({ length: { min: 10, max: 20 } }),
                  undefined,
                ]),
                url: faker.helpers.arrayElement([
                  faker.string.alpha({ length: { min: 10, max: 20 } }),
                  undefined,
                ]),
              },
              undefined,
            ]),
            quoteDate: faker.date.past().toISOString().split("T")[0],
            price: faker.number.float({
              min: undefined,
              max: undefined,
              fractionDigits: 2,
            }),
            discountType: faker.helpers.arrayElement([
              faker.helpers.arrayElement(Object.values(Type)),
              undefined,
            ]),
          })),
          undefined,
        ]),
        stats: faker.helpers.arrayElement([
          {
            [faker.string.alphanumeric(5)]: faker.number.float({
              min: undefined,
              max: undefined,
              fractionDigits: 2,
            }),
          },
          undefined,
        ]),
        quantityPerItem: faker.helpers.arrayElement([
          faker.number.float({
            min: undefined,
            max: undefined,
            fractionDigits: 2,
          }),
          undefined,
        ]),
        itemPerBundle: faker.helpers.arrayElement([
          faker.number.int({ min: undefined, max: undefined }),
          undefined,
        ]),
        tags: faker.helpers.arrayElement([
          Array.from(
            { length: faker.number.int({ min: 1, max: 10 }) },
            (_, i) => i + 1,
          ).map(() => faker.string.alpha({ length: { min: 10, max: 20 } })),
          undefined,
        ]),
      },
      undefined,
    ]),
    storeInfo: faker.helpers.arrayElement([
      {
        id: faker.helpers.arrayElement([
          faker.number.int({ min: undefined, max: undefined }),
          undefined,
        ]),
        name: faker.string.alpha({ length: { min: 10, max: 20 } }),
        address: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        url: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
      },
      { id: faker.number.int({ min: undefined, max: undefined }) },
    ]),
    quoteDate: faker.date.past().toISOString().split("T")[0],
    price: faker.number.float({
      min: undefined,
      max: undefined,
      fractionDigits: 2,
    }),
    discountType: faker.helpers.arrayElement([
      faker.helpers.arrayElement(Object.values(Type)),
      undefined,
    ]),
  }));

export const getGetApiProductSuggestResponseMock = (): string[] =>
  Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, () =>
    faker.word.sample(),
  );

export const getGetApiProductProductIdResponseMock = (
  overrideResponse: Partial<ProductInfo> = {},
): ProductInfo => ({
  id: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  name: faker.string.alpha({ length: { min: 1, max: 20 } }),
  imgUrl: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  desc: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  gtin: faker.helpers.arrayElement([
    faker.helpers.fromRegExp("^([0-9]d{8}|[0-9]{12}|[0-9]{13}|[0-9]{14})$"),
    undefined,
  ]),
  unit: faker.helpers.arrayElement(Object.values(Unit)),
  latestQuotes: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      id: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      storeInfo: faker.helpers.arrayElement([
        {
          id: faker.helpers.arrayElement([
            faker.number.int({ min: undefined, max: undefined }),
            undefined,
          ]),
          name: faker.string.alpha({ length: { min: 10, max: 20 } }),
          address: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
          ]),
          url: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
          ]),
        },
        undefined,
      ]),
      quoteDate: faker.date.past().toISOString().split("T")[0],
      price: faker.number.float({
        min: undefined,
        max: undefined,
        fractionDigits: 2,
      }),
      discountType: faker.helpers.arrayElement([
        faker.helpers.arrayElement(Object.values(Type)),
        undefined,
      ]),
    })),
    undefined,
  ]),
  stats: faker.helpers.arrayElement([
    {
      [faker.string.alphanumeric(5)]: faker.number.float({
        min: undefined,
        max: undefined,
        fractionDigits: 2,
      }),
    },
    undefined,
  ]),
  quantityPerItem: faker.helpers.arrayElement([
    faker.number.float({ min: undefined, max: undefined, fractionDigits: 2 }),
    undefined,
  ]),
  itemPerBundle: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  tags: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => faker.string.alpha({ length: { min: 10, max: 20 } })),
    undefined,
  ]),
  ...overrideResponse,
});

export const getGetApiProductProductIdChartResponseMock = (): ChartNode[] =>
  Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    index: faker.string.alpha({ length: { min: 10, max: 20 } }),
    value: faker.string.alpha({ length: { min: 10, max: 20 } }),
  }));

export const getGetApiProductProductIdQuoteHistResponseMock = (): QuoteDTO[] =>
  Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.helpers.arrayElement([
      faker.number.int({ min: undefined, max: undefined }),
      undefined,
    ]),
    productInfo: faker.helpers.arrayElement([
      {
        id: faker.helpers.arrayElement([
          faker.number.int({ min: undefined, max: undefined }),
          undefined,
        ]),
        name: faker.string.alpha({ length: { min: 1, max: 20 } }),
        imgUrl: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        desc: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        gtin: faker.helpers.arrayElement([
          faker.helpers.fromRegExp(
            "^([0-9]d{8}|[0-9]{12}|[0-9]{13}|[0-9]{14})$",
          ),
          undefined,
        ]),
        unit: faker.helpers.arrayElement(Object.values(Unit)),
        latestQuotes: faker.helpers.arrayElement([
          Array.from(
            { length: faker.number.int({ min: 1, max: 10 }) },
            (_, i) => i + 1,
          ).map(() => ({
            id: faker.helpers.arrayElement([
              faker.number.int({ min: undefined, max: undefined }),
              undefined,
            ]),
            storeInfo: faker.helpers.arrayElement([
              {
                id: faker.helpers.arrayElement([
                  faker.number.int({ min: undefined, max: undefined }),
                  undefined,
                ]),
                name: faker.string.alpha({ length: { min: 10, max: 20 } }),
                address: faker.helpers.arrayElement([
                  faker.string.alpha({ length: { min: 10, max: 20 } }),
                  undefined,
                ]),
                url: faker.helpers.arrayElement([
                  faker.string.alpha({ length: { min: 10, max: 20 } }),
                  undefined,
                ]),
              },
              undefined,
            ]),
            quoteDate: faker.date.past().toISOString().split("T")[0],
            price: faker.number.float({
              min: undefined,
              max: undefined,
              fractionDigits: 2,
            }),
            discountType: faker.helpers.arrayElement([
              faker.helpers.arrayElement(Object.values(Type)),
              undefined,
            ]),
          })),
          undefined,
        ]),
        stats: faker.helpers.arrayElement([
          {
            [faker.string.alphanumeric(5)]: faker.number.float({
              min: undefined,
              max: undefined,
              fractionDigits: 2,
            }),
          },
          undefined,
        ]),
        quantityPerItem: faker.helpers.arrayElement([
          faker.number.float({
            min: undefined,
            max: undefined,
            fractionDigits: 2,
          }),
          undefined,
        ]),
        itemPerBundle: faker.helpers.arrayElement([
          faker.number.int({ min: undefined, max: undefined }),
          undefined,
        ]),
        tags: faker.helpers.arrayElement([
          Array.from(
            { length: faker.number.int({ min: 1, max: 10 }) },
            (_, i) => i + 1,
          ).map(() => faker.string.alpha({ length: { min: 10, max: 20 } })),
          undefined,
        ]),
      },
      undefined,
    ]),
    storeInfo: faker.helpers.arrayElement([
      {
        id: faker.helpers.arrayElement([
          faker.number.int({ min: undefined, max: undefined }),
          undefined,
        ]),
        name: faker.string.alpha({ length: { min: 10, max: 20 } }),
        address: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        url: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
      },
      { id: faker.number.int({ min: undefined, max: undefined }) },
    ]),
    quoteDate: faker.date.past().toISOString().split("T")[0],
    price: faker.number.float({
      min: undefined,
      max: undefined,
      fractionDigits: 2,
    }),
    discountType: faker.helpers.arrayElement([
      faker.helpers.arrayElement(Object.values(Type)),
      undefined,
    ]),
  }));

export const getGetApiCommonLatestDealsMockHandler = (
  overrideResponse?:
    | QuoteResult
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<QuoteResult> | QuoteResult),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/common/latestDeals",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getGetApiCommonLatestDealsResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getGetApiProductAlertsMockHandler = (
  overrideResponse?:
    | QuoteDTO[]
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<QuoteDTO[]> | QuoteDTO[]),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/product/alerts",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getGetApiProductAlertsResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getGetApiProductExtSourcesMockHandler = (
  overrideResponse?:
    | string[]
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<string[]> | string[]),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/product/extSources",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getGetApiProductExtSourcesResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getGetApiProductGtinGtinMockHandler = (
  overrideResponse?:
    | ProductInfo
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ProductInfo> | ProductInfo),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/product/gtin/:gtin",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getGetApiProductGtinGtinResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getPostApiProductNewMockHandler = (
  overrideResponse?:
    | unknown
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<unknown> | unknown),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/api/product/new",
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};

export const getGetApiProductSearchMockHandler = (
  overrideResponse?:
    | ProductInfo[]
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ProductInfo[]> | ProductInfo[]),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/product/search",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getGetApiProductSearchResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getPostApiProductSearchExtMockHandler = (
  overrideResponse?:
    | QuoteDTO[]
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<QuoteDTO[]> | QuoteDTO[]),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/api/product/searchExt",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getPostApiProductSearchExtResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getGetApiProductSuggestMockHandler = (
  overrideResponse?:
    | string[]
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<string[]> | string[]),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/product/suggest",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getGetApiProductSuggestResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getGetApiProductProductIdMockHandler = (
  overrideResponse?:
    | ProductInfo
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ProductInfo> | ProductInfo),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/product/:productId",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getGetApiProductProductIdResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getGetApiProductProductIdChartMockHandler = (
  overrideResponse?:
    | ChartNode[]
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ChartNode[]> | ChartNode[]),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/product/:productId/chart",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getGetApiProductProductIdChartResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getPostApiProductProductIdEditMockHandler = (
  overrideResponse?:
    | unknown
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<unknown> | unknown),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/api/product/:productId/edit",
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};

export const getPostApiProductProductIdQuoteMockHandler = (
  overrideResponse?:
    | unknown
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<unknown> | unknown),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/api/product/:productId/quote",
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};

export const getGetApiProductProductIdQuoteHistMockHandler = (
  overrideResponse?:
    | QuoteDTO[]
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<QuoteDTO[]> | QuoteDTO[]),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/product/:productId/quoteHist",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getGetApiProductProductIdQuoteHistResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};
export const getPricekeepAPIMock = () => [
  getGetApiCommonLatestDealsMockHandler(),
  getGetApiProductAlertsMockHandler(),
  getGetApiProductExtSourcesMockHandler(),
  getGetApiProductGtinGtinMockHandler(),
  getPostApiProductNewMockHandler(),
  getGetApiProductSearchMockHandler(),
  getPostApiProductSearchExtMockHandler(),
  getGetApiProductSuggestMockHandler(),
  getGetApiProductProductIdMockHandler(),
  getGetApiProductProductIdChartMockHandler(),
  getPostApiProductProductIdEditMockHandler(),
  getPostApiProductProductIdQuoteMockHandler(),
  getGetApiProductProductIdQuoteHistMockHandler(),
];
