services:
  db:
    image: postgis/postgis:18-3.6-alpine
    healthcheck:
      test: pg_isready -U pricekeep -d pricekeep
      interval: 5s
      timeout: 3s
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pricekeep
      POSTGRES_PASSWORD: pricekeep-1234
      POSTGRES_DB: pricekeep
volumes:
  pgdata:
    driver: local