/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */

export type AlertAction = (typeof AlertAction)[keyof typeof AlertAction];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AlertAction = {
  SET: "SET",
  REMOVE: "REMOVE",
} as const;
