/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { Product } from "./product";

export interface Alert {
  product?: Product;
  targetPrice?: number;
}
