/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { WithDetail } from "./withDetail";
import type { WithId } from "./withId";

export type BaseEntity = WithDetail | WithId;
