/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { JavaTypeObject } from "./javaTypeObject";

export interface BasicValueConverterObjectObject {
  domainJavaType?: JavaTypeObject;
  relationalJavaType?: JavaTypeObject;
}
