/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { BatchKey } from "./batchKey";
import type { PreparedStatementGroup } from "./preparedStatementGroup";

export interface Batch {
  key?: BatchKey;
  statementGroup?: PreparedStatementGroup;
}
