/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */

export type CastType = (typeof CastType)[keyof typeof CastType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CastType = {
  STRING: "STRING",
  CLOB: "CLOB",
  BOOLEAN: "BOOLEAN",
  INTEGER_BOOLEAN: "INTEGER_BOOLEAN",
  YN_BOOLEAN: "YN_BOOLEAN",
  TF_BOOLEAN: "TF_BOOLEAN",
  INTEGER: "INTEGER",
  LONG: "LONG",
  FLOAT: "FLOAT",
  DOUBLE: "DOUBLE",
  FIXED: "FIXED",
  DATE: "DATE",
  TIME: "TIME",
  TIMESTAMP: "TIMESTAMP",
  OFFSET_TIMESTAMP: "OFFSET_TIMESTAMP",
  ZONE_TIMESTAMP: "ZONE_TIMESTAMP",
  JSON: "JSON",
  XML: "XML",
  NULL: "NULL",
  OTHER: "OTHER",
} as const;
