/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { DatabaseMetaData } from "./databaseMetaData";
import type { SQLWarning } from "./sQLWarning";
import type { ConnectionTypeMap } from "./connectionTypeMap";
import type { ConnectionClientInfo } from "./connectionClientInfo";
import type { ShardingKey } from "./shardingKey";

export interface Connection {
  autoCommit?: boolean;
  closed?: boolean;
  metaData?: DatabaseMetaData;
  readOnly?: boolean;
  catalog?: string;
  transactionIsolation?: number;
  warnings?: SQLWarning;
  typeMap?: ConnectionTypeMap;
  holdability?: number;
  clientInfo?: ConnectionClientInfo;
  schema?: string;
  networkTimeout?: number;
  shardingKey?: ShardingKey;
}
