/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { ResultSet } from "./resultSet";
import type { Connection } from "./connection";
import type { RowIdLifetime } from "./rowIdLifetime";

export interface DatabaseMetaData {
  uRL?: string;
  userName?: string;
  readOnly?: boolean;
  databaseProductName?: string;
  databaseProductVersion?: string;
  driverName?: string;
  driverVersion?: string;
  driverMajorVersion?: number;
  driverMinorVersion?: number;
  identifierQuoteString?: string;
  sQLKeywords?: string;
  numericFunctions?: string;
  stringFunctions?: string;
  systemFunctions?: string;
  timeDateFunctions?: string;
  searchStringEscape?: string;
  extraNameCharacters?: string;
  schemaTerm?: string;
  procedureTerm?: string;
  catalogTerm?: string;
  catalogAtStart?: boolean;
  catalogSeparator?: string;
  maxBinaryLiteralLength?: number;
  maxCharLiteralLength?: number;
  maxColumnNameLength?: number;
  maxColumnsInGroupBy?: number;
  maxColumnsInIndex?: number;
  maxColumnsInOrderBy?: number;
  maxColumnsInSelect?: number;
  maxColumnsInTable?: number;
  maxConnections?: number;
  maxCursorNameLength?: number;
  maxIndexLength?: number;
  maxSchemaNameLength?: number;
  maxProcedureNameLength?: number;
  maxCatalogNameLength?: number;
  maxRowSize?: number;
  maxStatementLength?: number;
  maxStatements?: number;
  maxTableNameLength?: number;
  maxTablesInSelect?: number;
  maxUserNameLength?: number;
  defaultTransactionIsolation?: number;
  schemas?: ResultSet;
  catalogs?: ResultSet;
  tableTypes?: ResultSet;
  typeInfo?: ResultSet;
  connection?: Connection;
  resultSetHoldability?: number;
  databaseMajorVersion?: number;
  databaseMinorVersion?: number;
  jDBCMajorVersion?: number;
  jDBCMinorVersion?: number;
  sQLStateType?: number;
  rowIdLifetime?: RowIdLifetime;
  clientInfoProperties?: ResultSet;
  maxLogicalLobSize?: number;
}
