/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { Quote } from "./quote";
import type { Type } from "./type";

export interface Discount {
  id?: number;
  quote?: Quote;
  type?: Type;
  saveValue?: number;
  salePrice?: number;
  multiBuyQuantity?: number;
}
