/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { PeriodLength } from "./periodLength";

export type GetApiProductProductIdQuoteHistParams = {
  id?: boolean;
  l?: PeriodLength;
};
