/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { TimeRange } from "./timeRange";

export type GetApiProductProductIdChartParams = {
  showDiscount?: boolean;
  tr: TimeRange;
};
