/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { JavaTypeJavaType } from "./javaTypeJavaType";
import type { JavaTypeJavaTypeClass } from "./javaTypeJavaTypeClass";
import type { MutabilityPlanObject1 } from "./mutabilityPlanObject1";
import type { ComparatorObject1 } from "./comparatorObject1";

export interface JavaType {
  javaType?: JavaTypeJavaType;
  javaTypeClass?: JavaTypeJavaTypeClass;
  typeName?: string;
  mutabilityPlan?: MutabilityPlanObject1;
  defaultValue?: unknown;
  longSqlLength?: number;
  comparator?: ComparatorObject1;
  temporalType?: boolean;
}
