/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { JavaTypeObjectJavaType } from "./javaTypeObjectJavaType";
import type { JavaTypeObjectJavaTypeClass } from "./javaTypeObjectJavaTypeClass";
import type { MutabilityPlanObject } from "./mutabilityPlanObject";
import type { ComparatorObject } from "./comparatorObject";

export interface JavaTypeObject {
  javaType?: JavaTypeObjectJavaType;
  javaTypeClass?: JavaTypeObjectJavaTypeClass;
  typeName?: string;
  mutabilityPlan?: MutabilityPlanObject;
  defaultValue?: unknown;
  longSqlLength?: number;
  comparator?: ComparatorObject;
  temporalType?: boolean;
}
