/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { JavaType } from "./javaType";
import type { JdbcType } from "./jdbcType";
import type { ValueExtractorObject } from "./valueExtractorObject";
import type { ValueBinder } from "./valueBinder";
import type { CastType } from "./castType";
import type { JdbcLiteralFormatter } from "./jdbcLiteralFormatter";
import type { JavaTypeObject } from "./javaTypeObject";
import type { BasicValueConverterObjectObject } from "./basicValueConverterObjectObject";
import type { JdbcMapping as __JdbcMapping } from "./jdbcMapping";

export interface JdbcMapping {
  javaTypeDescriptor?: JavaType;
  jdbcType?: JdbcType;
  jdbcValueExtractor?: ValueExtractorObject;
  jdbcValueBinder?: ValueBinder;
  castType?: CastType;
  jdbcLiteralFormatter?: JdbcLiteralFormatter;
  mappedJavaType?: JavaTypeObject;
  jdbcJavaType?: JavaTypeObject;
  valueConverter?: BasicValueConverterObjectObject;
  jdbcTypeCount?: number;
  singleJdbcMapping?: __JdbcMapping;
}
