/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { CastType } from "./castType";

export interface JdbcType {
  friendlyName?: string;
  jdbcTypeCode?: number;
  defaultSqlTypeCode?: number;
  ddlTypeCode?: number;
  integer?: boolean;
  float?: boolean;
  decimal?: boolean;
  number?: boolean;
  binary?: boolean;
  string?: boolean;
  stringLike?: boolean;
  temporal?: boolean;
  lob?: boolean;
  lobOrLong?: boolean;
  nationalized?: boolean;
  interval?: boolean;
  duration?: boolean;
  array?: boolean;
  castType?: CastType;
  comparable?: boolean;
  stringLikeExcludingClob?: boolean;
  spatial?: boolean;
  json?: boolean;
  implicitJson?: boolean;
  xml?: boolean;
  implicitXml?: boolean;
  boolean?: boolean;
  smallInteger?: boolean;
}
