/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { JobStatus } from "./jobStatus";
import type { LocalDateTime } from "./localDateTime";
import type { JobInfoParameters } from "./jobInfoParameters";

export interface JobInfo {
  readonly id: number;
  enabled?: boolean;
  name?: string;
  description?: string;
  /** @minLength 1 */
  readonly type: string;
  /** @minLength 1 */
  readonly frequency: string;
  /** @minLength 1 */
  readonly status: JobStatus;
  /** @minLength 1 */
  readonly lastResult: JobStatus;
  /** @minLength 1 */
  readonly lastRunTime: LocalDateTime;
  /** @minLength 1 */
  readonly nextExecTime: LocalDateTime;
  parameters?: JobInfoParameters;
}
