/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { LocalDateTime } from "./localDateTime";

export interface JobInfo {
  id?: number;
  enabled?: boolean;
  name?: string;
  description?: string;
  lastRunTime?: LocalDateTime;
  nextExecTime?: LocalDateTime;
}
