/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */

export type JobStatus = (typeof JobStatus)[keyof typeof JobStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const JobStatus = {
  RUNNING: "RUNNING",
  PAUSED: "PAUSED",
  DISABLED: "DISABLED",
  ENABLED: "ENABLED",
  COMPLETED: "COMPLETED",
  ERROR: "ERROR",
} as const;
