/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { SelectablePath } from "./selectablePath";
import type { JdbcMapping } from "./jdbcMapping";

export interface KeyColumn {
  containingTableExpression?: string;
  selectionExpression?: string;
  selectableName?: string;
  selectablePath?: SelectablePath;
  customReadExpression?: string;
  customWriteExpression?: string;
  writeExpression?: string;
  formula?: boolean;
  nullable?: boolean;
  insertable?: boolean;
  updateable?: boolean;
  partitioned?: boolean;
  columnDefinition?: string;
  length?: number;
  precision?: number;
  scale?: number;
  temporalPrecision?: number;
  lob?: boolean;
  columnName?: string;
  jdbcMapping?: JdbcMapping;
}
