/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { KeyColumn } from "./keyColumn";

export interface KeyDetails {
  columnCount?: number;
  keyColumns?: KeyColumn[];
}
