/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { MutationType } from "./mutationType";
import type { Expectation } from "./expectation";

export interface MutationDetails {
  mutationType?: MutationType;
  expectation?: Expectation;
  customSql?: string;
  callable?: boolean;
  dynamicMutation?: boolean;
}
