/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */

export type MutationType = (typeof MutationType)[keyof typeof MutationType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MutationType = {
  INSERT: "INSERT",
  UPDATE: "UPDATE",
  DELETE: "DELETE",
} as const;
