/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */

export type PeriodLength = (typeof PeriodLength)[keyof typeof PeriodLength];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PeriodLength = {
  WEEK: "WEEK",
  MONTH: "MONTH",
  QUARTER: "QUARTER",
  YEAR: "YEAR",
} as const;
