/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { Unit } from "./unit";
import type { SimpleQuoteDTO } from "./simpleQuoteDTO";
import type { PostApiProductNew201Stats } from "./postApiProductNew201Stats";

export type PostApiProductNew201 = {
  readonly id?: number;
  /** @minLength 1 */
  name: string;
  imgUrl?: string;
  desc?: string;
  /**
   * @minLength 8
   * @maxLength 14
   * @pattern ^([0-9]{8}|[0-9]{12,14})$
   */
  gtin?: string;
  unit: Unit;
  readonly latestQuotes?: readonly SimpleQuoteDTO[];
  readonly stats?: PostApiProductNew201Stats;
  quantityPerItem?: number;
  itemPerBundle?: number;
  tags?: string[];
};
