/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { TableMapping } from "./tableMapping";
import type { PreparedStatement } from "./preparedStatement";
import type { Expectation } from "./expectation";

export interface PreparedStatementDetails {
  mutatingTableDetails?: TableMapping;
  sqlString?: string;
  statement?: PreparedStatement;
  expectation?: Expectation;
  callable?: boolean;
}
