/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { ProductInfo } from "./productInfo";

export interface ProductResult {
  productList?: ProductInfo[];
  totalRecords?: number;
  totalPages?: number;
  pageSize?: number;
  currentPage?: number;
}
