/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */

export interface ProductQuoteImportBatchDTO {
  name?: string;
  description?: string;
  cronTrigger?: string;
  storeList?: number[];
  keyword?: string;
}
