/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { Quote } from "./quote";
import type { Unit } from "./unit";
import type { ProductPriceStats } from "./productPriceStats";

export interface Product {
  id?: number;
  name?: string;
  description?: string;
  gtin?: string;
  priceQuotes?: Quote[];
  packageSize?: number;
  itemPerPackage?: number;
  unit?: Unit;
  unitScale?: number;
  tags?: string[];
  priceStats?: ProductPriceStats;
  imgPath?: string;
}
