/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */

export type ProductInfoUndefined =
  (typeof ProductInfoUndefined)[keyof typeof ProductInfoUndefined];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductInfoUndefined = {
  ProductInfo: "ProductInfo",
} as const;
