/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { Unit } from "./unit";
import type { SimpleQuoteDTO } from "./simpleQuoteDTO";
import type { ProductInfoStats } from "./productInfoStats";

export interface ProductInfo {
  readonly id?: number;
  /** @minLength 1 */
  name: string;
  imgUrl?: string;
  desc?: string;
  /**
   * @minLength 8
   * @maxLength 14
   * @pattern ^([0-9]d{8}|[0-9]{12}|[0-9]{13}|[0-9]{14})$
   */
  gtin?: string;
  unit: Unit;
  readonly latestQuotes?: readonly SimpleQuoteDTO[];
  readonly stats?: ProductInfoStats;
  quantityPerItem?: number;
  itemPerBundle?: number;
  tags?: string[];
}
