/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { QuoteDTO } from "./quoteDTO";

export interface QuoteResult {
  results?: QuoteDTO[];
}
