/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { StoreInfo } from "./storeInfo";
import type { WithId } from "./withId";

export type QuoteDTOStoreInfo = StoreInfo | WithId;
