/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { ProductInfo } from "./productInfo";
import type { QuoteDTOStoreInfo } from "./quoteDTOStoreInfo";
import type { LocalDate } from "./localDate";
import type { Type } from "./type";

export interface QuoteDTO {
  readonly id?: number;
  productInfo?: ProductInfo;
  storeInfo: QuoteDTOStoreInfo;
  quoteDate: LocalDate;
  price: number;
  discountType?: Type;
}
