/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { Store } from "./store";
import type { Product } from "./product";
import type { LocalDate } from "./localDate";
import type { Discount } from "./discount";
import type { Source } from "./source";

export interface Quote {
  quoteStore?: Store;
  product?: Product;
  quoteDate?: LocalDate;
  price: number;
  discount?: Discount;
  quoteSource?: Source;
  unitPrice?: number;
  discountedUnitPrice?: number;
}
