/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { SQLWarning } from "./sQLWarning";
import type { ResultSetMetaData } from "./resultSetMetaData";
import type { Statement } from "./statement";

export interface ResultSet {
  warnings?: SQLWarning;
  cursorName?: string;
  metaData?: ResultSetMetaData;
  beforeFirst?: boolean;
  afterLast?: boolean;
  first?: boolean;
  last?: boolean;
  row?: number;
  fetchDirection?: number;
  fetchSize?: number;
  type?: number;
  concurrency?: number;
  statement?: Statement;
  holdability?: number;
  closed?: boolean;
}
