/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */

export type RowIdLifetime = (typeof RowIdLifetime)[keyof typeof RowIdLifetime];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RowIdLifetime = {
  ROWID_UNSUPPORTED: "ROWID_UNSUPPORTED",
  ROWID_VALID_OTHER: "ROWID_VALID_OTHER",
  ROWID_VALID_SESSION: "ROWID_VALID_SESSION",
  ROWID_VALID_TRANSACTION: "ROWID_VALID_TRANSACTION",
  ROWID_VALID_FOREVER: "ROWID_VALID_FOREVER",
} as const;
