/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { SelectablePath as __SelectablePath } from "./selectablePath";

export interface SelectablePath {
  root?: boolean;
  parent?: __SelectablePath;
  name?: string;
  index?: number;
  parts?: SelectablePath[];
  selectableName?: string;
  localName?: string;
  fullPath?: string;
}
