/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { StoreInfo } from "./storeInfo";
import type { LocalDate } from "./localDate";
import type { Type } from "./type";

export interface SimpleQuoteDTO {
  readonly id?: number;
  storeInfo?: StoreInfo;
  quoteDate: LocalDate;
  price: number;
  discountType?: Type;
}
