/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { StoreInfo } from "./storeInfo";
import type { LocalDate } from "./localDate";
import type { Type } from "./type";

export interface SimpleQuoteDTO {
  productName?: string;
  productImgPath?: string;
  productId?: number;
  storeInfo?: StoreInfo;
  quoteDate: LocalDate;
  price: number;
  unitScale?: number;
  unitPrice: number;
  unit?: string;
  discountType?: Type;
  discountPrice?: number;
  multibuyQuantity?: number;
}
