/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */

export type Source = (typeof Source)[keyof typeof Source];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Source = {
  USER: "USER",
  SYSTEM: "SYSTEM",
} as const;
