/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { SQLWarning } from "./sQLWarning";
import type { ResultSet } from "./resultSet";
import type { Connection } from "./connection";

export interface Statement {
  maxFieldSize?: number;
  maxRows?: number;
  escapeProcessing?: boolean;
  queryTimeout?: number;
  warnings?: SQLWarning;
  cursorName?: string;
  resultSet?: ResultSet;
  updateCount?: number;
  moreResults?: boolean;
  fetchDirection?: number;
  fetchSize?: number;
  resultSetConcurrency?: number;
  resultSetType?: number;
  connection?: Connection;
  generatedKeys?: ResultSet;
  resultSetHoldability?: number;
  closed?: boolean;
  poolable?: boolean;
  closeOnCompletion?: boolean;
  largeUpdateCount?: number;
  largeMaxRows?: number;
}
