/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { StoreGroup } from "./storeGroup";

export interface Store {
  id?: number;
  name?: string;
  url?: string;
  address?: string;
  internalId?: string;
  group?: StoreGroup;
}
