/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { Store } from "./store";

export interface StoreGroup {
  id?: number;
  name?: string;
  branches?: Store[];
  iconPath?: string;
}
