/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { KeyDetails } from "./keyDetails";
import type { MutationDetails } from "./mutationDetails";

export interface TableMapping {
  keyDetails?: KeyDetails;
  tableName?: string;
  relativePosition?: number;
  optional?: boolean;
  inverse?: boolean;
  identifierTable?: boolean;
  insertDetails?: MutationDetails;
  updateDetails?: MutationDetails;
  cascadeDeleteEnabled?: boolean;
  deleteDetails?: MutationDetails;
}
