/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */

export type TimeRange = (typeof TimeRange)[keyof typeof TimeRange];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TimeRange = {
  ONE_MONTH: "ONE_MONTH",
  THREE_MONTH: "THREE_MONTH",
  SIX_MONTH: "SIX_MONTH",
  TWELVE_MONTH: "TWELVE_MONTH",
} as const;
