/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */

export type Unit = (typeof Unit)[keyof typeof Unit];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Unit = {
  PER_ITEM: "PER_ITEM",
  PER_KG: "PER_KG",
  PER_100G: "PER_100G",
  PER_G: "PER_G",
  PER_LITRE: "PER_LITRE",
  PER_METRE: "PER_METRE",
} as const;
