/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */

export type WithIdType = (typeof WithIdType)[keyof typeof WithIdType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WithIdType = {
  id: "id",
} as const;
