/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * pricekeep API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */

export type WithDetailType =
  (typeof WithDetailType)[keyof typeof WithDetailType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WithDetailType = {
  detail: "detail",
} as const;
